In [2]:
#загрузка первой анкеты
import json
import pandas as pd
import nltk
data = open('anketa.json', encoding='utf-8')
data_2 = json.load(data)
df = pd.DataFrame.from_dict(pd.json_normalize(data_2), orient="columns")
df

,Имя,Фамилия,Опыт работы,Образование,Проекты,Дополнительная информация,Контактная информация.Электронная почта,Контактная информация.Номер телефона,Навыки.Язык программирования,Навыки.Фреймворки,Навыки.Базы данных,Навыки.Работа с API,Навыки.Инструменты,Языки.Русский,Языки.Английский
0,Иван,Иванов,3,АСУ НКН МИСИС,"[{'Название проекта': 'Empty', 'Описание проек...",,sobakadog.ru,+78006661488,Python,"Django, Flask, FastAPI","SQL (MySQL, PostgreSQL), NoSQL (MongoDB)",RESTful API,"Git, Docker",Родной,Свободно

In [3]:
#загрузка второй анкеты
data_a1 = open('анкета1.json', encoding='utf-8')
data_a1 = json.load(data_a1)
data_a1 = pd.DataFrame.from_dict(pd.json_normalize(data_a1), orient="columns")
data_a1

,Имя,Фамилия,Опыт работы,Образование,Проекты,Дополнительная информация,Контактная информация.Электронная почта,Контактная информация.Номер телефона,Навыки.Язык программирования,Навыки.Фреймворки,Навыки.Базы данных,Навыки.Работа с API,Навыки.Инструменты,Языки.Русский,Языки.Английский
0,Анна,Петрова,5,Московский Государственный Университет,"[{'Название проекта': 'Умный дом', 'Описание п...",Активно участвую в сообществе Python-разработч...,anna.petrova@email.com,+79012345678,Python,"Django, Flask, FastAPI","SQL (PostgreSQL, SQLite), NoSQL (MongoDB)","RESTful API, GraphQL","Git, Docker, Jenkins",Родной,Свободно

In [4]:
df = df.fillna(value="")
df

,Имя,Фамилия,Опыт работы,Образование,Проекты,Дополнительная информация,Контактная информация.Электронная почта,Контактная информация.Номер телефона,Навыки.Язык программирования,Навыки.Фреймворки,Навыки.Базы данных,Навыки.Работа с API,Навыки.Инструменты,Языки.Русский,Языки.Английский
0,Иван,Иванов,3,АСУ НКН МИСИС,"[{'Название проекта': 'Empty', 'Описание проек...",,sobakadog.ru,+78006661488,Python,"Django, Flask, FastAPI","SQL (MySQL, PostgreSQL), NoSQL (MongoDB)",RESTful API,"Git, Docker",Родной,Свободно

In [5]:
data_a1 = data_a1.fillna(value="")
data_a1

,Имя,Фамилия,Опыт работы,Образование,Проекты,Дополнительная информация,Контактная информация.Электронная почта,Контактная информация.Номер телефона,Навыки.Язык программирования,Навыки.Фреймворки,Навыки.Базы данных,Навыки.Работа с API,Навыки.Инструменты,Языки.Русский,Языки.Английский
0,Анна,Петрова,5,Московский Государственный Университет,"[{'Название проекта': 'Умный дом', 'Описание п...",Активно участвую в сообществе Python-разработч...,anna.petrova@email.com,+79012345678,Python,"Django, Flask, FastAPI","SQL (PostgreSQL, SQLite), NoSQL (MongoDB)","RESTful API, GraphQL","Git, Docker, Jenkins",Родной,Свободно

In [6]:
'''
сделать проверку на дубликаты в датафрейме и итоговой анкете(?)
df.is_duplicate.value_counts(normalize=True)
'''

'\nсделать проверку на дубликаты в датафрейме и итоговой анкете(?)\ndf.is_duplicate.value_counts(normalize=True)\n'

In [7]:
from nltk.tokenize import RegexpTokenizer
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = stopwords.words('russian')
filtered_tokens = []
def preprocess1(df):
    df = df.to_string()
    tokenizer = RegexpTokenizer(r'\w+')
    df = tokenizer.tokenize(df)
    df = [token.lower() for token in df]
    for token in df:
        if token not in stop_words:
            filtered_tokens.append(token)
    return filtered_tokens
print(preprocess1(df))

['имя', 'фамилия', 'опыт', 'работы', 'образование', 'проекты', 'дополнительная', 'информация', 'контактная', 'информация', 'электронная', 'почта', 'контактная', 'информация', 'номер', 'телефона', 'навыки', 'язык', 'программирования', 'навыки', 'фреймворки', 'навыки', 'базы', 'данных', 'навыки', 'работа', 'api', 'навыки', 'инструменты', 'языки', 'русский', 'языки', 'английский', '0', 'иван', 'иванов', '3', 'асу', 'нкн', 'мисис', 'название', 'проекта', 'empty', 'описание', 'проекта', 'роль', 'backend', 'python', 'использованные', 'технологии', 'sobakadog', 'ru', '78006661488', 'python', 'django', 'flask', 'fastapi', 'sql', 'mysql', 'postgresql', 'nosql', 'mongodb', 'restful', 'api', 'git', 'docker', 'родной', 'свободно']

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sholo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [8]:
#Вторая анкета, предобработка
filtered_tokens_2=[]
def preprocess2(data_a1):
    data_a1 = data_a1.to_string()
    tokenizer = RegexpTokenizer(r'\w+')
    data_a1 = tokenizer.tokenize(data_a1)
    data_a1 = [token.lower() for token in data_a1]
    for token in data_a1:
        if token not in stop_words:
            filtered_tokens_2.append(token)
    return filtered_tokens_2
print(preprocess2(data_a1))

['имя', 'фамилия', 'опыт', 'работы', 'образование', 'проекты', 'дополнительная', 'информация', 'контактная', 'информация', 'электронная', 'почта', 'контактная', 'информация', 'номер', 'телефона', 'навыки', 'язык', 'программирования', 'навыки', 'фреймворки', 'навыки', 'базы', 'данных', 'навыки', 'работа', 'api', 'навыки', 'инструменты', 'языки', 'русский', 'языки', 'английский', '0', 'анна', 'петрова', '5', 'московский', 'государственный', 'университет', 'название', 'проекта', 'умный', 'дом', 'описание', 'проекта', 'разработка', 'системы', 'умного', 'дома', 'использованием', 'django', 'iot', 'устройств', 'роль', 'middle', 'backend', 'python', 'developer', 'использованные', 'технологии', 'django', 'python', 'iot', 'restful', 'api', 'название', 'проекта', 'sample', 'e', 'commerce', 'platform', 'описание', 'проекта', 'разработка', 'полноценной', 'электронной', 'торговой', 'платформы', 'использованием', 'django', 'роль', 'middle', 'backend', 'python', 'developer', 'использованные', 'технологии', 'django', 'python', 'postgresql', 'название', 'проекта', 'анализ', 'данных', 'реальном', 'времени', 'описание', 'проекта', 'создание', 'системы', 'анализа', 'данных', 'реальном', 'времени', 'финансовой', 'аналитики', 'роль', 'backend', 'developer', 'использованные', 'технологии', 'python', 'kafka', 'postgresql', 'активно', 'участвую', 'сообществе', 'python', 'разработчиков', 'увлекаюсь', 'машинным', 'обучением', 'искусственным', 'интеллектом', 'anna', 'petrova', 'email', 'com', '79012345678', 'python', 'django', 'flask', 'fastapi', 'sql', 'postgresql', 'sqlite', 'nosql', 'mongodb', 'restful', 'api', 'graphql', 'git', 'docker', 'jenkins', 'родной', 'свободно']

In [9]:
del filtered_tokens_2[:34]
filtered_tokens_2

['анна',
 'петрова',
 '5',
 'московский',
 'государственный',
 'университет',
 'название',
 'проекта',
 'умный',
 'дом',
 'описание',
 'проекта',
 'разработка',
 'системы',
 'умного',
 'дома',
 'использованием',
 'django',
 'iot',
 'устройств',
 'роль',
 'middle',
 'backend',
 'python',
 'developer',
 'использованные',
 'технологии',
 'django',
 'python',
 'iot',
 'restful',
 'api',
 'название',
 'проекта',
 'sample',
 'e',
 'commerce',
 'platform',
 'описание',
 'проекта',
 'разработка',
 'полноценной',
 'электронной',
 'торговой',
 'платформы',
 'использованием',
 'django',
 'роль',
 'middle',
 'backend',
 'python',
 'developer',
 'использованные',
 'технологии',
 'django',
 'python',
 'postgresql',
 'название',
 'проекта',
 'анализ',
 'данных',
 'реальном',
 'времени',
 'описание',
 'проекта',
 'создание',
 'системы',
 'анализа',
 'данных',
 'реальном',
 'времени',
 'финансовой',
 'аналитики',
 'роль',
 'backend',
 'developer',
 'использованные',
 'технологии',
 'python',
 'kafka',
 'postgresql',
 'активно',
 'участвую',
 'сообществе',
 'python',
 'разработчиков',
 'увлекаюсь',
 'машинным',
 'обучением',
 'искусственным',
 'интеллектом',
 'anna',
 'petrova',
 'email',
 'com',
 '79012345678',
 'python',
 'django',
 'flask',
 'fastapi',
 'sql',
 'postgresql',
 'sqlite',
 'nosql',
 'mongodb',
 'restful',
 'api',
 'graphql',
 'git',
 'docker',
 'jenkins',
 'родной',
 'свободно']

In [10]:
del filtered_tokens[:34]
filtered_tokens

['иван',
 'иванов',
 '3',
 'асу',
 'нкн',
 'мисис',
 'название',
 'проекта',
 'empty',
 'описание',
 'проекта',
 'роль',
 'backend',
 'python',
 'использованные',
 'технологии',
 'sobakadog',
 'ru',
 '78006661488',
 'python',
 'django',
 'flask',
 'fastapi',
 'sql',
 'mysql',
 'postgresql',
 'nosql',
 'mongodb',
 'restful',
 'api',
 'git',
 'docker',
 'родной',
 'свободно']

In [55]:
#TfidfVectorizer
#cosine_similarity
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import linear_kernel

def text_similarity(filtered_tokens, filtered_tokens_2):
    vectorizer = TfidfVectorizer()
    vector1 = vectorizer.fit_transform(filtered_tokens)
    print(np.shape(vector1))
    vector2 = vectorizer.transform(filtered_tokens_2)
    print(np.shape(vector2))
    similarity = linear_kernel(vector1, vector2)

    return similarity
print(text_similarity(filtered_tokens,filtered_tokens_2))

(34, 31)
(113, 31)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]

NameError: name 'vector1' is not defined

In [41]:
import numpy as np
import sentence_transformers
from sentence_transformers import SentenceTransformer
from transformers import BertTokenizer, BertModel
import torch
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')#токенизация с помощью BERT

In [42]:
indexed_tokens = tokenizer.convert_tokens_to_ids(filtered_tokens)#первая анкета

In [43]:
indexed_tokens

[100,
 100,
 1017,
 100,
 100,
 100,
 100,
 100,
 4064,
 100,
 100,
 100,
 100,
 18750,
 100,
 100,
 100,
 21766,
 100,
 18750,
 100,
 100,
 100,
 29296,
 100,
 100,
 100,
 100,
 100,
 17928,
 100,
 100,
 100,
 100]

In [44]:
indexed_tokens2 = tokenizer.convert_tokens_to_ids(filtered_tokens_2)#вторая анкета
indexed_tokens2

[100,
 100,
 1019,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 2690,
 100,
 18750,
 9722,
 100,
 100,
 100,
 18750,
 100,
 100,
 17928,
 100,
 100,
 7099,
 1041,
 6236,
 4132,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 2690,
 100,
 18750,
 9722,
 100,
 100,
 100,
 18750,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 9722,
 100,
 100,
 18750,
 100,
 100,
 100,
 100,
 100,
 18750,
 100,
 100,
 100,
 100,
 100,
 100,
 4698,
 100,
 10373,
 4012,
 100,
 18750,
 100,
 100,
 100,
 29296,
 100,
 100,
 100,
 100,
 100,
 17928,
 100,
 100,
 100,
 11098,
 100,
 100]

In [48]:
import torch
tokens_tensor1 = torch.FloatTensor([indexed_tokens])
tokens_tensor1

tensor([[  100.,   100.,  1017.,   100.,   100.,   100.,   100.,   100.,  4064.,
           100.,   100.,   100.,   100., 18750.,   100.,   100.,   100., 21766.,
           100., 18750.,   100.,   100.,   100., 29296.,   100.,   100.,   100.,
           100.,   100., 17928.,   100.,   100.,   100.,   100.]])

In [49]:
tokens_tensor2 = torch.FloatTensor([indexed_tokens2])
tokens_tensor2

tensor([[  100.,   100.,  1019.,   100.,   100.,   100.,   100.,   100.,   100.,
           100.,   100.,   100.,   100.,   100.,   100.,   100.,   100.,   100.,
           100.,   100.,   100.,  2690.,   100., 18750.,  9722.,   100.,   100.,
           100., 18750.,   100.,   100., 17928.,   100.,   100.,  7099.,  1041.,
          6236.,  4132.,   100.,   100.,   100.,   100.,   100.,   100.,   100.,
           100.,   100.,   100.,  2690.,   100., 18750.,  9722.,   100.,   100.,
           100., 18750.,   100.,   100.,   100.,   100.,   100.,   100.,   100.,
           100.,   100.,   100.,   100.,   100.,   100.,   100.,   100.,   100.,
           100.,   100.,   100.,  9722.,   100.,   100., 18750.,   100.,   100.,
           100.,   100.,   100., 18750.,   100.,   100.,   100.,   100.,   100.,
           100.,  4698.,   100., 10373.,  4012.,   100., 18750.,   100.,   100.,
           100., 29296.,   100.,   100.,   100.,   100.,   100., 17928.,   100.,
           100.,   100., 11098.,   100.,   100.]])

In [17]:
#segment ids
segments_ids = [1] * len(filtered_tokens)
segments_ids2 = [1] * len(filtered_tokens_2)
segments_ids, segments_ids2

([1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1])

In [18]:
#тензоры 
tokens_segment1 = torch.tensor([segments_ids])
tokens_segment2 = torch.tensor([segments_ids2])

In [19]:
#модель BERT
model = BertModel.from_pretrained('bert-base-uncased',output_hidden_states=True)
model.eval()

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): BertPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

In [ ]:
'''Recommendation system based on dataset, example:
def get_recommendations(title, cosine_sim, indices):
    # Get the index of the movie that matches the title
    idx = indices[title]
    # Get the pairwsie similarity scores
    sim_scores = list(enumerate(cosine_sim[idx]))
    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    # Get the scores for 10 most similar movies
    sim_scores = sim_scores[1:11]
    # Get the movie indices
    talk_indices = [i[0] for i in sim_scores]
    # Return the top 10 most similar movies
    return ted['title'].iloc[talk_indices]
    indices = pd.Series(ted.index, index=ted['title']).drop_duplicates()
transcripts = ted['transcript']
tfidf = TfidfVectorizer(stop_words='english')

# Construct the TF-IDF matrix
tfidf_matrix = tfidf.fit_transform(transcripts)

# Generate the cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

# Generate recommendations
print(get_recommendations('5 ways to kill your dreams', cosine_sim, indices))
'''

In [72]:
vector1 = vector1.reshape(-1,1)
print(np.shape(vector1))

(1054, 1)

In [102]:
import torch
import torch.nn.functional as F
vectorizer = TfidfVectorizer()
vector1 = vectorizer.fit_transform(filtered_tokens)
vector2 = vectorizer.transform(filtered_tokens_2)
vector1 = vector1.reshape(-1,1)
vector2 = vector2.reshape(1,-1)
print(np.shape(vector1),np.shape(vector2))
vector1 = vector1.toarray()
vector2 = vector2.toarray()
vector1 = vector1.flatten()
vector2 = vector2.flatten()
tensor2 = torch.FloatTensor(vector2)
tensor = torch.FloatTensor(vector1)
result = F.cosine_similarity(tensor, tensor2)
result

(1054, 1) (1, 3503)

RuntimeError: The size of tensor a (1054) must match the size of tensor b (3503) at non-singleton dimension 0